- name: Deploy webapp
  become: true
  copy:
    src: ../webapp/go/isuconquest
    dest: /home/isucon/webapp/go/
  notify: restart_webapp
- name: Deploy init.sh
  become: true
  copy:
    src: ../webapp/sql/init.sh
    dest: /home/isucon/webapp/sql/
- name: Deploy 3_schema_exclude_user_presents.sql
  become: true
  copy:
    src: ../webapp/sql/3_schema_exclude_user_presents.sql
    dest: /home/isucon/webapp/sql/
- name: Deploy 4_alldata_exclude_user_presents
  become: true
  copy:
    src: "{{ item }}"
    dest: /home/isucon/webapp/sql/
  with_fileglob:
    - "../webapp/sql/4_alldata_exclude_user_presents*"
- name: Deploy 5_user_presents_not_receive_data
  become: true
  copy:
    src: "{{ item }}"
    dest: /home/isucon/webapp/sql/
  with_fileglob:
    - "../webapp/sql/5_user_presents_not_receive_data*"
- name: Deploy env
  become: true
  copy:
    src: ../provisioning/packer/ansible/roles/xbuild/files/home/isucon/env
    dest: /home/isucon/env
