all:
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  children:
    nginx:
      hosts:
        nginx01:
          ansible_host: 127.0.0.1
    app:
      hosts:
        app01:
          ansible_host: 127.0.0.1
        app02:
          ansible_host: 127.0.0.1
        app03:
          ansible_host: 127.0.0.1
    db:
      hosts:
        db01:
          ansible_host: 127.0.0.1
    memcached:
      hosts:
        memcached01:
          ansible_host: 127.0.0.1
    redis:
      hosts:
        redis01:
          ansible_host: 127.0.0.1
