all:
  children:
    bench:
      hosts:
        bench01:
          ansible_host: 18.178.128.76
    nginx:
      hosts:
        nginx01:
          ansible_host: 54.250.23.164
    webapp:
      hosts:
        webapp01:
          ansible_host: 54.250.23.164
    db:
      hosts:
        db01:
          ansible_host: 175.41.242.148
        db02:
          ansible_host: 18.178.208.176
    pprotein:
      hosts:
        pprotein01:
          ansible_host: 35.79.145.123
    # memcached:
      # hosts:
        # memcached01:
          # ansible_host: 127.0.0.1
    # redis:
      # hosts:
        # redis01:
          # ansible_host: 127.0.0.1
