- name: Install unzip
  become: true
  apt:
    name: unzip
    state: present
    update_cache: true
- name: Install slp
  become: true
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/bin:/home/isucon/local/node/bin:/home/isucon/local/golang/bin"
  shell:
    chdir: /home/isucon/
    cmd: "{{ item }}"
  with_items:
    - "wget https://github.com/tkuchiki/slp/releases/download/v0.2.0/slp_linux_amd64.zip"
    - "unzip slp_linux_amd64.zip"
    - "mv ./slp /usr/local/bin/slp"
